git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
gui:
  nerdFontsVersion: "3"  
  theme:
      selectedLineBgColor:
        - reverse
os:
editPreset: 'nvim'
